spring.application.name=order-management

# Pastikan port 8080 sudah kamu kill, atau ganti jadi 8081
server.port=8080

# Koneksi MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/order_management_db
spring.datasource.username=root
spring.datasource.password=

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
